# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/clinux01/Escritorio/eci35_hetprog-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/clinux01/Escritorio/eci35_hetprog-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clinux01/Escritorio/eci35_hetprog-main/CMakeFiles /home/clinux01/Escritorio/eci35_hetprog-main/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/clinux01/Escritorio/eci35_hetprog-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named add_array_sycl

# Build rule for target.
add_array_sycl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_array_sycl
.PHONY : add_array_sycl

# fast build rule for target.
add_array_sycl/fast:
	$(MAKE) -f lab1/CMakeFiles/add_array_sycl.dir/build.make lab1/CMakeFiles/add_array_sycl.dir/build
.PHONY : add_array_sycl/fast

#=============================================================================
# Target rules for targets named add_array_serial_skeleton

# Build rule for target.
add_array_serial_skeleton: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_array_serial_skeleton
.PHONY : add_array_serial_skeleton

# fast build rule for target.
add_array_serial_skeleton/fast:
	$(MAKE) -f lab1/CMakeFiles/add_array_serial_skeleton.dir/build.make lab1/CMakeFiles/add_array_serial_skeleton.dir/build
.PHONY : add_array_serial_skeleton/fast

#=============================================================================
# Target rules for targets named pi_taylor_sycl

# Build rule for target.
pi_taylor_sycl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_taylor_sycl
.PHONY : pi_taylor_sycl

# fast build rule for target.
pi_taylor_sycl/fast:
	$(MAKE) -f lab2/CMakeFiles/pi_taylor_sycl.dir/build.make lab2/CMakeFiles/pi_taylor_sycl.dir/build
.PHONY : pi_taylor_sycl/fast

#=============================================================================
# Target rules for targets named pi_taylor_serial

# Build rule for target.
pi_taylor_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_taylor_serial
.PHONY : pi_taylor_serial

# fast build rule for target.
pi_taylor_serial/fast:
	$(MAKE) -f lab2/CMakeFiles/pi_taylor_serial.dir/build.make lab2/CMakeFiles/pi_taylor_serial.dir/build
.PHONY : pi_taylor_serial/fast

#=============================================================================
# Target rules for targets named mul_array_sycl_optimized

# Build rule for target.
mul_array_sycl_optimized: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mul_array_sycl_optimized
.PHONY : mul_array_sycl_optimized

# fast build rule for target.
mul_array_sycl_optimized/fast:
	$(MAKE) -f lab3/CMakeFiles/mul_array_sycl_optimized.dir/build.make lab3/CMakeFiles/mul_array_sycl_optimized.dir/build
.PHONY : mul_array_sycl_optimized/fast

#=============================================================================
# Target rules for targets named mul_array_sycl

# Build rule for target.
mul_array_sycl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mul_array_sycl
.PHONY : mul_array_sycl

# fast build rule for target.
mul_array_sycl/fast:
	$(MAKE) -f lab3/CMakeFiles/mul_array_sycl.dir/build.make lab3/CMakeFiles/mul_array_sycl.dir/build
.PHONY : mul_array_sycl/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f lab4/CMakeFiles/run.dir/build.make lab4/CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named report

# Build rule for target.
report: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 report
.PHONY : report

# fast build rule for target.
report/fast:
	$(MAKE) -f lab4/CMakeFiles/report.dir/build.make lab4/CMakeFiles/report.dir/build
.PHONY : report/fast

#=============================================================================
# Target rules for targets named fpga

# Build rule for target.
fpga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpga
.PHONY : fpga

# fast build rule for target.
fpga/fast:
	$(MAKE) -f lab4/CMakeFiles/fpga.dir/build.make lab4/CMakeFiles/fpga.dir/build
.PHONY : fpga/fast

#=============================================================================
# Target rules for targets named add_array_pipes_sycl.fpga

# Build rule for target.
add_array_pipes_sycl.fpga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_array_pipes_sycl.fpga
.PHONY : add_array_pipes_sycl.fpga

# fast build rule for target.
add_array_pipes_sycl.fpga/fast:
	$(MAKE) -f lab4/CMakeFiles/add_array_pipes_sycl.fpga.dir/build.make lab4/CMakeFiles/add_array_pipes_sycl.fpga.dir/build
.PHONY : add_array_pipes_sycl.fpga/fast

#=============================================================================
# Target rules for targets named fpga_emu

# Build rule for target.
fpga_emu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpga_emu
.PHONY : fpga_emu

# fast build rule for target.
fpga_emu/fast:
	$(MAKE) -f lab4/CMakeFiles/fpga_emu.dir/build.make lab4/CMakeFiles/fpga_emu.dir/build
.PHONY : fpga_emu/fast

#=============================================================================
# Target rules for targets named add_array_pipes_sycl.fpga_emu

# Build rule for target.
add_array_pipes_sycl.fpga_emu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_array_pipes_sycl.fpga_emu
.PHONY : add_array_pipes_sycl.fpga_emu

# fast build rule for target.
add_array_pipes_sycl.fpga_emu/fast:
	$(MAKE) -f lab4/CMakeFiles/add_array_pipes_sycl.fpga_emu.dir/build.make lab4/CMakeFiles/add_array_pipes_sycl.fpga_emu.dir/build
.PHONY : add_array_pipes_sycl.fpga_emu/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... add_array_sycl"
	@echo "... add_array_serial_skeleton"
	@echo "... pi_taylor_sycl"
	@echo "... pi_taylor_serial"
	@echo "... mul_array_sycl_optimized"
	@echo "... mul_array_sycl"
	@echo "... run"
	@echo "... report"
	@echo "... fpga"
	@echo "... add_array_pipes_sycl.fpga"
	@echo "... fpga_emu"
	@echo "... add_array_pipes_sycl.fpga_emu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

